// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {
    verifyDelegationProofES256,
    verifyDelegationProofKS256
} from "@univocity/checkpoints/lib/delegationVerifier.sol";

/// @notice FOR-332 / plan-0050 R3: contract acceptance of proofs signed by
///    canopy delegation-cose (TypeScript). Vectors generated by
///    packages/libs/delegation-cose/scripts/export-onchain-vectors.mjs and
///    checked in at test/fixtures/onchain-delegation-vectors.json.
contract TsOnchainDelegationVectorsTest is Test {
    // Shared scope from the TS fixture (log id 16 bytes right-aligned).
    bytes32 internal constant LOG_ID =
        bytes32(uint256(0x101112131415161718191a1b1c1d1e1f));
    uint64 internal constant MMR_START = 3;
    uint64 internal constant MMR_END = 1_099_511_627_776; // 1 << 40
    bytes32 internal constant DELEGATED_X = bytes32(
        hex"a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf"
    );
    bytes32 internal constant DELEGATED_Y = bytes32(
        hex"c0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedf"
    );

    function test_tsSigned_ks256_proof_verifies_on_chain() public {
        address root = address(0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266);
        this._verifyKs256(
            hex"a1013a00010106",
            hex"6425b9686f7fa0744f8381fc1e83731d6a3c4abbcb04701e4e570c8d3df6020d0e002bfe26b29be3864061049a79e22f120bafe8db5a26c0868aa2f54d6d9a9b01",
            root
        );
    }

    function test_tsSigned_es256_proof_verifies_on_chain() public {
        bytes32 rootX = bytes32(
            hex"52120be34ce3826d9dbbfa9cd014fb73fe03889ac3df248d93947593c06b2246"
        );
        bytes32 rootY = bytes32(
            hex"5c36828a7cdbfa9954be6339cc1acdb6593185b58e1ec5926dc143afddd7f0bf"
        );
        this._verifyEs256(
            hex"a10126",
            hex"7c8c3e6ea32f089a6a6989a217562d7ee58bbca586a18407b136abda390de5e748fda465e1db436c1b380ad8ea059985d192492a9a99904149275d76c91004d1",
            rootX,
            rootY
        );
    }

    /// @dev External so calldata args reach the free functions.
    function _verifyKs256(
        bytes calldata protectedHeader,
        bytes calldata signature,
        address root
    ) external view {
        verifyDelegationProofKS256(
            protectedHeader,
            MMR_START,
            MMR_END,
            signature,
            LOG_ID,
            MMR_START,
            root,
            DELEGATED_X,
            DELEGATED_Y
        );
    }

    /// @dev External so calldata args reach the free functions.
    function _verifyEs256(
        bytes calldata protectedHeader,
        bytes calldata signature,
        bytes32 rootX,
        bytes32 rootY
    ) external view {
        verifyDelegationProofES256(
            protectedHeader,
            MMR_START,
            MMR_END,
            signature,
            LOG_ID,
            MMR_START,
            rootX,
            rootY,
            DELEGATED_X,
            DELEGATED_Y
        );
    }
}
