#!/usr/bin/env python3
"""Generate all KAT tables and vectors for Solidity algorithm tests.

Single entry point for plan-0020: index_height table, leaf_count table,
39-node MMR hashes, and pointer to consistent_roots vectors.

Usage:
    python3 -m algorithms.gen_all_kat          # print all to stdout
    python3 -m algorithms.gen_all_kat --summary # print summary only

Canonical 39-node MMR matches Python db.KatDB / Go draft_kat39_test.go
KAT39Nodes (leaves = SHA256(index as 8-byte BE), interior = SHA256(pos||L||R)).
"""

import argparse
import sys

from .binutils import index_height
from .peaks import leaf_count, peaks


def main():
    ap = argparse.ArgumentParser(description="Generate KAT tables for Solidity tests")
    ap.add_argument(
        "--summary",
        action="store_true",
        help="Print only summary and regeneration commands",
    )
    args = ap.parse_args()

    if args.summary:
        print("# KAT regeneration summary")
        print("# Run: python3 -m algorithms.gen_all_kat")
        print("# Run: python3 -m algorithms.gen_consistent_roots_vectors")
        print("# Solidity tests: LibBinUtils_indexHeight (heights 0..38),")
        print("#   peaks.t.sol (leafCount 1..39), Kat39Inclusion (39 hashes),")
        print("#   consistentRoots (from gen_consistent_roots_vectors).")
        return 0

    # -------------------------------------------------------------------------
    # Index height table (MMR indices 0..38) — for LibBinUtils_indexHeight.t.sol
    # Source: Python tests.py test_index_heights; Go IndexHeight
    # -------------------------------------------------------------------------
    print("// Index height KAT: indexHeight(i) for i in 0..38")
    print("// Use in test_indexHeight_pythonTable() (LibBinUtils_indexHeight.t.sol)")
    heights = [index_height(i) for i in range(39)]
    print("// uint8[39] expectedHeights = [")
    print("//   " + ", ".join(str(h) for h in heights))
    print("// ];")
    print()

    # -------------------------------------------------------------------------
    # Leaf count table (mmrSize 1..39) — for peaks.t.sol test_leafCount_pythonTable
    # Source: Python index_values_table[1]; Go expectLeafCounts
    # -------------------------------------------------------------------------
    print("// Leaf count KAT: leafCount(mmrSize) for mmrSize 1..39")
    print("// Use in test_leafCount_pythonTable() (peaks.t.sol)")
    counts = [leaf_count(s) for s in range(1, 40)]
    print("// uint256[39] expectedLeafCounts = [")
    print("//   " + ", ".join(str(c) for c in counts))
    print("// ];")
    print()

    # -------------------------------------------------------------------------
    # Peak indices per complete MMR size (reference)
    # -------------------------------------------------------------------------
    print("// Peak indices (complete MMR sizes): peaks(mmrSize-1) for mmrSize in")
    print("// 1,3,4,7,8,10,11,15,16,18,19,22,23,25,26,31,32,34,35,38,39")
    complete_sizes = [1, 3, 4, 7, 8, 10, 11, 15, 16, 18, 19, 22, 23, 25, 26, 31, 32, 34, 35, 38, 39]
    for s in complete_sizes:
        p = peaks(s - 1)
        print(f"//   mmrSize={s} -> peaks = {p}")
    print()

    # -------------------------------------------------------------------------
    # 39-node hashes: generated by build_mmr(39) in gen_consistent_roots_vectors
    # or match Go KAT39Nodes. Solidity embeds them in Kat39Inclusion.t.sol.
    # -------------------------------------------------------------------------
    print("// 39-node hashes: from algorithms.gen_consistent_roots_vectors build_mmr(39)")
    print("// or Go draft_kat39_test.go KAT39Nodes. Embedded in test/algorithms/Kat39Inclusion.t.sol")
    print()

    print("// Consistent roots vectors: run python3 -m algorithms.gen_consistent_roots_vectors")
    print("// to emit Solidity snippets for test/algorithms/consistentRoots.t.sol")
    return 0


if __name__ == "__main__":
    sys.exit(main())
